CREATE DATABASE CLIENTE_CADASTRO;

USE CLIENTE_CADASTRO;

CREATE TABLE CLIENTE(
	IDCLIENTE INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50),
	IDADE VARCHAR(50),
	TELEFONE VARCHAR(50),
	PRIMARY KEY (IDCLIENTE)
);
// sql do projeto